### ISSUE TITLE
configmaps is forbidden

### ISSUE THREAD

**Issue by tofutim** [wireapp/wire-docs#50]
Hi, I am working on installing the demo server on an Ubuntu 18.04 VM running on VMWare Fusion on my mac. I am using the docker image (Docker for Mac) according to the instructions. (One issue I ran into earlier was that I had to specify the ansible_user as root, which has SSH access...) Here's where I'm at.
```
bash-4.4# helm upgrade --install databases-ephemeral wire/databases-ephemeral --wait

UPGRADE FAILED
ROLLING BACK
Error: configmaps is forbidden: User "system:serviceaccount:kube-system:default" cannot list resource "configmaps" in API group "" in the namespace "kube-system"
Error: UPGRADE FAILED: configmaps is forbidden: User "system:serviceaccount:kube-system:default" cannot list resource "configmaps" in API group "" in the namespace "kube-system"
```

**Comment by tofutim** [comment]
I used 
```
bash-4.4# kubectl create clusterrolebinding default-cluster-admin --clusterrole=cluster-admin --serviceaccount=kube-system:default
clusterrolebinding.rbac.authorization.k8s.io/default-cluster-admin created
``
per https://github.com/helm/helm/issues/5100#issuecomment-533787541 to overcome it. Not sure if 
(1) default never had that power or (2) a new serviceaccount should have been created with this power or (3) default lost the power in the latest version.

Versions:
```
bash-4.4# kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:23:09Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:14:56Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
bash-4.4# helm version
Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
```

**Comment by lucendio** [comment]
Hi @tofutim,

Since you are using Helm v2, the general first step (not wire-specific) would be to initialize Helm (`helm init`). This would also install Tiller, Helm's server component. Depending on your individual setup and the way how you bootstrapped it, the starting point for installing Wire might differ.

In general, it is considered good practice to not install workload in Kubernetes's `default` namespace. We tried to address this in the grey box *Note* in the [*How to start installing charts from wire*](https://docs.wire.com/how-to/install/helm.html#how-to-start-installing-charts-from-wire) section. But it seems this part might deserve some improvements.

That said, you seem to have solved the issues in your particular case yourself. So, unless you follow up on this, I would consider this issues solved?
